'use client';
import { useParams, useRouter } from 'next/navigation';
import * as React from 'react';
import { Alert, Badge, Button, Card, CardHeader, ProgressBar, Skeleton, StatusBadge } from '@/components/ui';
import { IconArrowLeft, IconCamera, IconDownload, IconMapPin } from '@/components/icons';
import { InspectionDetail, api, readableError } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { formatDate, formatDateTime, formatMoney, fullName, humanise, statusLabel, statusTone } from '@/lib/format';

export default function InspectionDetailPage(){
 const p=useParams<{id:string}>(),router=useRouter(),{user,can}=useAuth();const[inspection,setInspection]=React.useState<InspectionDetail|null>(null);const[error,setError]=React.useState<string|null>(null);const[notice,setNotice]=React.useState<string|null>(null);const[busy,setBusy]=React.useState(false);const[photoUrls,setPhotoUrls]=React.useState<Record<string,string>>({});
 const load=React.useCallback(async()=>{try{const d=await api.get<InspectionDetail>(`/inspections/${p.id}`);setInspection(d);if(d.photos.length){const photos=await api.get<Array<{id:string;url:string}>>(`/inspections/${p.id}/photos`);setPhotoUrls(Object.fromEntries(photos.map(x=>[x.id,x.url])));}}catch(e){setError(readableError(e));}},[p.id]);React.useEffect(()=>{void load();},[load]);
 if(!inspection)return error?<Alert title="Could not load this inspection">{error}</Alert>:<div className="space-y-4"><Skeleton className="h-10 w-64"/><Skeleton className="h-32 rounded-2xl"/><Skeleton className="h-[500px] rounded-2xl"/></div>;
 const i=inspection, awaiting=['SUBMITTED','RESUBMITTED','UNDER_REVIEW'].includes(i.status),isOwn=i.inspector?.id===user?.id,canReview=can('reviews.decide')&&awaiting&&!isOwn,canGenerate=can('reports.generate')&&['APPROVED','REPORT_GENERATED'].includes(i.status);const reports=[...i.reports].sort((a,b)=>new Date(b.generatedAt).getTime()-new Date(a.generatedAt).getTime());const finals=reports.filter(r=>r.reportNumber.startsWith('RPT-'));const drafts=reports.filter(r=>r.reportNumber.startsWith('DRF-'));const latestFinal=finals[0],latestDraft=drafts[0];const vals=new Map(i.values.map(v=>[v.field.code,v]));const raw=(code:string):unknown=>{const v=vals.get(code);return v?.valueText??v?.valueNumber??v?.valueBool??v?.valueJson??null};const improved=String(raw('PROPERTY_STATUS')??'').toUpperCase()==='IMPROVED';const land=raw(improved?'IMPROVED_LAND_VALUE':'LAND_ESTIMATED_VALUE'),building=raw('MAIN_BUILDING_VALUE'),total=raw(improved?'IMPROVED_TOTAL_VALUE':'LAND_ESTIMATED_VALUE');const valueMoney=(v:unknown)=>v===null||v===undefined||v===''?'—':formatMoney(String(v));
 const download=async(id:string)=>{try{const r=await api.get<{url:string}>(`/reports/${id}/download`);window.open(r.url,'_blank','noopener');}catch(e){setError(readableError(e));}};
 const regenerate=async()=>{setBusy(true);setError(null);try{await api.post(`/inspections/${i.id}/report`);await load();setNotice('Final report regenerated from the current professional review data.');}catch(e){setError(readableError(e));}finally{setBusy(false);}};
 return <div className="space-y-4 py-2"><button type="button" onClick={()=>router.push('/inspections')} className="inline-flex items-center gap-1.5 text-sm text-ink-muted hover:text-ink"><IconArrowLeft className="h-4 w-4"/>Back to inspections</button>
 <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-xl font-semibold text-ink">{i.inspectionNumber}</h1><StatusBadge tone={statusTone(i.status)}>{statusLabel(i.status)}</StatusBadge><Badge tone="neutral">{humanise(i.priority)}</Badge></div><p className="mt-1.5 text-sm text-ink-muted">{i.loanReference} · {i.property.reference}</p><div className="mt-4 flex flex-wrap gap-x-8 gap-y-2"><Fact label="Branch" value={i.branch.code}/><Fact label="Inspector" value={fullName(i.inspector)}/><Fact label="Reviewer" value={fullName(i.reviewer)}/><Fact label="Due" value={formatDate(i.dueDate)}/></div></div><div className="flex flex-wrap gap-2">{canReview&&<Button variant="primary" onClick={()=>router.push(`/inspections/${i.id}/review`)}>Edit inspection</Button>}{latestDraft&&<Button variant="secondary" icon={<IconDownload className="h-4 w-4"/>} onClick={()=>void download(latestDraft.id)}>Download draft</Button>}{canGenerate&&<Button variant="secondary" loading={busy} onClick={()=>void regenerate()}>{latestFinal?'Regenerate':'Generate report'}</Button>}{latestFinal&&<Button loading={busy} icon={<IconDownload className="h-4 w-4"/>} onClick={()=>void download(latestFinal.id)}>Download final</Button>}</div></div></Card>
 {error&&<Alert title="Action failed" onDismiss={()=>setError(null)}>{error}</Alert>}{notice&&<Alert tone="success" title={notice} onDismiss={()=>setNotice(null)}/>}<div className="grid gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2">
 <Card><CardHeader title="Completeness" action={<span className="text-xl font-semibold text-ink">{i.completeness.percentage}%</span>}/><div className="px-5 pb-5"><ProgressBar percentage={i.completeness.percentage}/></div></Card>
 <div className="grid gap-4 sm:grid-cols-2"><Card><CardHeader title="Property"/><dl className="space-y-2.5 px-5 pb-5 text-sm"><Detail label="Reference" value={i.property.reference}/><Detail label="Type" value={i.property.propertyType}/><Detail label="Address" value={i.property.addressLine}/><Detail label="Location" value={[i.property.province,i.property.district,i.property.sector,i.property.cell].filter(Boolean).join(' · ')||'—'}/><Detail label="UPI" value={i.property.titleNumber||'—'}/></dl></Card><Card><CardHeader title="Owner / Client"/>{i.owner?<dl className="space-y-2.5 px-5 pb-5 text-sm"><Detail label="Name" value={i.owner.fullName}/><Detail label="Phone" value={i.owner.phone||'—'}/><Detail label="Email" value={i.owner.email||'—'}/><Detail label="Occupancy" value={humanise(i.owner.occupancyStatus)}/><Detail label="Ownership" value={humanise(i.owner.ownershipType)}/></dl>:<p className="px-5 pb-5 text-sm text-ink-faint">No owner/client recorded.</p>}</Card></div>
 <Card><CardHeader title="Recorded information"/><div className="grid gap-x-8 gap-y-2.5 px-5 pb-5 text-sm sm:grid-cols-2">{i.values.map(v=><Detail key={v.id} label={v.field.label} value={displayValue(v)}/>)}</div></Card>
 <Card><CardHeader title="Condition assessment"/>{i.assessments.length?<div className="space-y-2 px-5 pb-5">{i.assessments.map(a=><div key={a.id} className="rounded-xl bg-surface-2 px-4 py-3"><div className="flex justify-between gap-3"><span className="text-sm font-medium text-ink">{a.categoryName}</span><span className="text-sm text-ink-muted">{a.rating===null?'—':`${a.rating}/5`} · {humanise(a.condition)}</span></div>{a.notes&&<p className="mt-1 text-sm text-ink-muted">{a.notes}</p>}</div>)}</div>:<p className="px-5 pb-5 text-sm text-ink-faint">No assessment categories.</p>}</Card>
 <Card><CardHeader title="Photographic evidence" description={`${i.photos.length} photograph${i.photos.length===1?'':'s'}`}/>{i.photos.length?<div className="grid grid-cols-2 gap-3 px-5 pb-5 sm:grid-cols-3">{i.photos.map(ph=><div key={ph.id} className="overflow-hidden rounded-xl border border-line"><div className="aspect-[4/3] bg-surface-2">{photoUrls[ph.id]?<img src={photoUrls[ph.id]} alt={ph.caption||humanise(ph.category)} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs text-ink-faint">Loading…</div>}</div><div className="px-3 py-2 text-xs"><p className="font-medium text-ink">{humanise(ph.category)}</p><p className="text-ink-faint">{ph.capturedAt?formatDate(ph.capturedAt):'—'}</p></div></div>)}</div>:<p className="px-5 pb-5 text-sm text-ink-faint"><IconCamera className="mr-2 inline h-4 w-4"/>No photographs uploaded.</p>}</Card>
 </div><div className="space-y-4"><Card><CardHeader title="Location verification"/><div className="px-5 pb-5">{i.proximity?<><Badge tone={i.proximity.verdict==='AT_PROPERTY'?'success':i.proximity.verdict==='NEARBY'?'warning':'neutral'}>{humanise(i.proximity.verdict)}</Badge><dl className="mt-3 space-y-2 text-sm"><Detail label="Coordinates" value={i.locations[0]?`${Number(i.locations[0].latitude).toFixed(5)}, ${Number(i.locations[0].longitude).toFixed(5)}`:'—'}/><Detail label="Accuracy" value={i.locations[0]?.accuracyM?`${Math.round(i.locations[0].accuracyM)} m`:'—'}/><Detail label="Captured" value={i.locations[0]?formatDateTime(i.locations[0].capturedAt):'—'}/></dl></>:<p className="text-sm text-ink-faint">No GPS reading captured.</p>}</div></Card>
 <Card><CardHeader title="Valuation"/><div className="px-5 pb-5"><dl className="space-y-3 text-sm">{land!==null&&land!==undefined&&<Detail label="Land value" value={valueMoney(land)}/>} {improved&&<Detail label="Main building value" value={valueMoney(building)}/>}<div className="border-t border-line pt-3"><Detail label="Total estimated value" value={valueMoney(total)}/></div></dl></div></Card>
 <Card><CardHeader title="Reports" description="One current final report is maintained for the inspection."/><div className="space-y-2 px-5 pb-5">{reports.map(r=><div key={r.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-3"><div><div className="flex items-center gap-2"><Badge tone={r.reportNumber.startsWith('DRF-')?'warning':'success'}>{r.reportNumber.startsWith('DRF-')?'Draft':'Final'}</Badge><span className="text-sm font-semibold text-ink">{r.reportNumber}</span></div><p className="text-2xs text-ink-faint">{formatDate(r.generatedAt)}</p></div><Button size="sm" variant="secondary" onClick={()=>void download(r.id)}>Download</Button></div>)}{!reports.length&&<p className="text-sm text-ink-faint">No reports yet.</p>}</div></Card>
 <Card><CardHeader title="Approval"/><dl className="space-y-2.5 px-5 pb-5 text-sm"><Detail label="Submitted" value={formatDateTime(i.submittedAt)}/><Detail label="Approved" value={formatDateTime(i.approvedAt)}/><Detail label="Reviewer" value={fullName(i.reviewer)}/></dl></Card></div></div></div>;
}
function displayValue(v:InspectionDetail['values'][number]):string{if(v.valueText)return v.valueText;if(v.valueNumber!==null&&v.valueNumber!==undefined)return String(v.valueNumber);if(v.valueDate)return formatDate(v.valueDate);if(v.valueBool!==null&&v.valueBool!==undefined)return v.valueBool?'Yes':'No';if(Array.isArray(v.valueJson))return v.valueJson.join(', ');if(v.valueJson!==null&&v.valueJson!==undefined)return typeof v.valueJson==='object'?JSON.stringify(v.valueJson):String(v.valueJson);return '—';}
function Fact({label,value}:{label:string;value:string}){return <div><p className="text-2xs text-ink-faint">{label}</p><p className="mt-0.5 text-sm font-medium text-ink">{value}</p></div>}
function Detail({label,value}:{label:string;value:string|null|undefined}){return <div className="flex justify-between gap-4"><dt className="text-ink-muted">{label}</dt><dd className="text-right font-medium text-ink">{value||'—'}</dd></div>}
